### ISSUE TITLE
Latest release seems to be overriding the Bulma default is-link color 

### ISSUE THREAD

**Issue by bpepple** [lemonsaurus/django-simple-bulma#76]
Noticed that django-simple-bulma has changed the default "is-link" modifier color. The default used to be light blue, but with version 2.4.0, it has changed to a light purple (which is what I believe you use on your Python Dischord site). Haven't dug into the code yet, but I'm guessing maybe your site's css scheme might have been shipped.

**Comment by lemonsaurus** [comment]
interesting. thanks for the report, will investigate.

**Comment by lemonsaurus** [comment]
@bpepple could I get some hex values for the colors you're seeing?

There's no way Python Discord's site CSS scheme could have shipped, since it's in an entirely separate repository on a different org. I don't set any kind of default overrides here. The only thing that really changed in 2.4.0 is that we updated to a newer version of Bulma, so the most likely culprit is that this is behavior that changed in one of the Bulma releases over the past 10 months.

if you have a before and after hex value that would be helpful, though.

The default that Bulma lists in its documentation for `$link` is this:
![image](https://user-images.githubusercontent.com/2098517/120098540-c0161700-c136-11eb-91c5-ac63491bf073.png)

**Hex**: 4E78BC
**RGB**: 78, 120, 188

If you're seeing something different than that, well, then yes, that's weird.

**Comment by bpepple** [comment]
So, in my production site the default is-link color is #3273dc.

![production](https://user-images.githubusercontent.com/8381/120106495-1a10df80-c12b-11eb-99f8-c6a185c88fae.png)

And in my testing with the new bulma the is-link color is #485fc7

![testing](https://user-images.githubusercontent.com/8381/120106545-5cd2b780-c12b-11eb-8bcb-0d0a0af673a0.png)

Not quite sure how the default is-link color has changed between the two.

**Comment by lemonsaurus** [comment]
that is quite interesting. I can't find any references to `485fc7` neither in `django-simple-bulma` or in `bulma` itself, so it feels like it must be coming from your `BULMA_SETTINGS`, can you post those?

**Comment by lemonsaurus** [comment]
No, okay, I figured this out. 

If we look at Bulmas [initial variable definitions](https://github.com/jgthms/bulma/blob/master/sass/utilities/initial-variables.sass), we can see that `$blue: hsl(229, 53%,  53%)`, which is the HSL equivalent of #485fc7. 

Before Bulma v9, this color was in fact  #3273DC, which can be seen in [this pull request](https://github.com/jgthms/bulma/pull/3249/).

When we updated `django-simple-bulma` to v2.4.0, we also upgraded to Bulma 0.9.2, so this all adds up. This color did change, but it's not something I did but something Bulma did.

Anyway, I recommend you simply define your own link color in `BULMA_SETTINGS` if you'd like something other than the new Bulma default. You can just define the `blue` variable, and set it back to `#3273dc` if you prefer that.

**Comment by lemonsaurus** [comment]
Here's an example of how you can define this variable using `BULMA_SETTINGS` in your `settings.py`:

```py
BULMA_SETTINGS = {
  "variables": {
    "blue": "#3273dc",
  }
}
```

**Comment by bpepple** [comment]
Cool. Thanks!

**Comment by lemonsaurus** [comment]
No problem, thanks for the report!
